Community\Lib\Entity\Campaign:
  exclusion_policy: ALL
  xml_root_name: campaign
  properties:
    name:
      expose: true
      type: string
      groups: [standard, restapi]
  relations:
    -
      rel: self
      href:
        route: get_campaign
        parameters:
          id: expr(object.id)
        absolute: true
